### ISSUE TITLE
error establishing a database connection on http://www.libresprite.org/

### ISSUE THREAD

**Issue by WebDragon** [LibreSprite/LibreSprite#101]
the web page linked in the repository's main page is not currently working and this is a heads-up regarding that

**Comment by maujin111** [comment]
Thanks for the notice, we will try to solve it as soon as possible. Meanwhile the[ Github page](https://libresprite.github.io/) is available

**Comment by nanoslayer** [comment]
Please consider using a static website. Static websites are simpler to deploy and harder to exploit, and there are a lot of options for hosting. Plus, it would eliminate the spam problems.

The wiki can be moved to GitHub, and discussions can take place on a mailing list or on GitHub.

**Comment by JamesK89** [comment]
So I am the web host and unfortunately I hadn't a lot of time to look at it due to recent life events but I it appears that the Wiki was getting hit hard by spam bots which was crashing the database server. For now I've disabled access to the Wiki but I'm thinking it might be a good idea to move the Wiki to someplace else as @nanoslayer mentioned.

**Comment by maujin111** [comment]
Current site:  https://libresprite.github.io
