### ISSUE TITLE
Add plugin support

### ISSUE THREAD

**Issue by 3prm3** [LibreSprite/LibreSprite#122]

**Comment by Zughy** [comment]
Hello, scripting has been enabled again since https://github.com/LibreSprite/LibreSprite/commit/d7073645d13d88e965e5d3e243323713b6911cba. Also, @felipemanga is currently working on improving the current scripting system. Is this what you wanted or do you mean actual plugins, like LibreSprite extensions?

**Comment by Zughy** [comment]
I'm closing this one as there is not enough information to understand the request. If OP wants to add something, we now have a separate repo for feature requests where he can open one: https://github.com/LibreSprite/LibreSprite-proposals/
