### ISSUE TITLE
Remove useless palettes

### ISSUE THREAD

**Issue by Zughy** [LibreSprite/LibreSprite#126]
In 3 years of Aseprite/Libresprite I've never find myself using palettes such as:
- a64
- apple-ii
- arne-paldac
- atari ones
- commodore-plus4
- gameboy-color-type1
- google-ui
- vga-13h
- web-safe-colors
- x11
(and it's not thorough)

I think that, especially the ones with more than 32 colours, aren't just kind of pointless, but also a bad example for the ones who start with pixel art; as it's a common mistake to use a lot of similar colours even for simple drawings. Therefore palettes like arne-paldac, ataris, commodore-plus4, google-ui, nes-ntsc, vga-13h, web-safe-colors and x11 are more harmful than useful.

**But some of these are made for people that want to recreate retro console graphics**
Yes, but we're talking about a niche. Especially if we consider that lo-spec has a lot of awesome super-used palettes that, on the contrary, are not even listed here (like Endesga ones, Rosy 42 or, well, mine zughy 32)

I suggest to remove AT LEAST the ones listed above. I could go more radical, but it's up to the devs

**Comment by jjhaggar** [comment]
They are a really good help for people who want to recreate graphics on those old systems. It's not a good idea to remove a feature just because not everybody use it. We should be inclusive with people, not the opposite. 

On the other hand, I think it would be really nice to include the palettes you mentioned :) Could you maybe make/add them and then make a pull request, please?

**Comment by maujin111** [comment]
I think your request should be considered for the next release. Personally, I use the google-ui palette, but removing those palettes must be put to vote
