### ISSUE TITLE
old application name on panel (linux / gnome-desktop)

### ISSUE THREAD

**Issue by workingJ** [LibreSprite/LibreSprite#228]
##### LibreSprite version
```
LibreSprite-4fc8d53-x86_64.AppImage
```

##### Describe the bug

"Allegro" as Appliccation name in Activity-Panel

##### To Reproduce

Run a Pop-OS installation and start the libresprite Appimage.

##### Expected behaviour

should reade libresprite i guess

##### OS/Hardware
- Operative System: Pop!_OS 21.04 x86_64
- CPU: Intel i5-7300U (4) @ 3.500GHz

##### Screenshots  

![libresprite_issue](https://user-images.githubusercontent.com/19818596/133832548-35303a3d-38b3-41de-8e5b-20d82e31ab15.png)

Edit: added Appimage version, Quotationmarks, image edit

**Comment by Zughy** [comment]
Huh, I have Pop!_OS but I didn't notice. I can confirm the missing icon though. I'll test it in a couple days

**Comment by Zughy** [comment]
Ok, two things:
- I have Pop!_OS 21.04 but I can't find the option to see the name of the active window on top (and by default it doesn't show any)
- that release is pretty old (it's also still using Allegro as a backend, when we moved to SDL a few days ago). Can you try to [compile it](https://github.com/LibreSprite/LibreSprite/blob/master/INSTALL.md) and tell us if it keeps acting the same? Otherwise, we're going to release a beta release soon-ish and you can try with that

**Comment by maujin111** [comment]
Fixed with the implement of sdl2 on the new pre-release https://github.com/LibreSprite/LibreSprite/releases/tag/v1.2.1-Beta

**Comment by Zughy** [comment]
That pre-release is not up to date with SDL2. Also, we have no proof SDL2 has fixed it

**Comment by maujin111** [comment]
I just uploaded the sdl2 version this morning, did you download the appimage and test it?

**Comment by maujin111** [comment]
check this release please 
https://github.com/LibreSprite/LibreSprite/releases/tag/v1.0-beta.1

**Comment by workingJ** [comment]
Good work!
the the application has now the right name in the top panel.

the ugly preview-window-dragging-bug is gone, i can now move it fluently around!
thx! :>
