### ISSUE TITLE
Incorrect version in title bar and About window

### ISSUE THREAD

**Issue by NSobolew** [LibreSprite/LibreSprite#312]
LibreSprite v1.0, Windows 32 and 64

I downloaded version 1.0, but in title bar and About window, written version 1.2 which was during development

![image](https://user-images.githubusercontent.com/7355002/142808889-607314b2-af97-4915-8382-a8e8da377579.png)

**Comment by Zughy** [comment]
Hello and thanks for the report.
Yes, that's my fault when I've manually created the release. I hadn't any Windows on hand so I attached the previous precompiled version (where just a couple commits are missing). I'm planning to implement an automatised CD for Windows, so this will be fixed in the next (pre)release
