### ISSUE TITLE
when i launch it says File skins/Aseprite Theme Pack/sheet.png not found 

### ISSUE THREAD

**Issue by ayleejsjsk** [LibreSprite/LibreSprite#389]
when i try to launch aseprite, it says File skins/AsepriteThemePack/sheet.png not found. i am on windows 10

**Comment by jjhaggar** [comment]
This is LibreSprite, not Aseprite, though ^^U
Did you try downloading the last LibreSprite build from here? https://github.com/LibreSprite/LibreSprite/releases/latest (you probably need 
LibreSprite-Windows-x86_64.zip, or LibreSprite-Windows-x86_32.zip if your system is not 64 bits).
Also, you can come to the Discord server if you want so the feedback to give about this problem is faster/easier.

**Comment by ayleejsjsk** [comment]
alright, will do. thanks!

**Comment by jjhaggar** [comment]
It looks like it's solved now :)
![image](https://user-images.githubusercontent.com/4078392/215407531-ae6175b6-11b2-495d-bb18-fc31d251beda.png)

Somebody with admin superpowers, please close the issue ^^
