### ISSUE TITLE
Very low performance

### ISSUE THREAD

**Issue by jucogjucogi** [LibreSprite/LibreSprite#395]
libresprite is a good alt to aseprite, but when i make a new canvas it severely lags. that hard that it's impossible to draw.
i use **Windows 10(earlier) and 11, i3-2120 and GTX 750 ti**.

**Comment by felipemanga** [comment]
Are you using the v1.0 release?

**Comment by jucogjucogi** [comment]
yes

**Comment by jucogjucogi** [comment]
also it only lags in canvas area_ when i move cursor to everything else everything is normal

**Comment by dishb** [comment]
I would also like to report low performance on `macOS 12.6.6` (Intel Core i5 Macbook Air) I'm using whatever the latest version is for Libresprite macOS.

**Comment by dishb** [comment]
> seems like the problem is with events or some thing? not sure will need to look in the source.

Most of the lag is when the mouse is over the canvas. When using any sort of tool (brush, line, etc.) or when dragging the preview window around the canvas.

**Comment by hankster112** [comment]
Same issue on Debian Linux, built from the most recent commit as of writing. Same issues that @dishb has.
Debian 12 Bookworm
Ryzen 7 2700
MSI RX 580 4GB

**Comment by dishb** [comment]
Maybe an issue with memory?

**Comment by AMAIOLAMO** [comment]
I am also having the same issue again but on Arch linux with Integrated intel Arc Graphics and I have 2880x1920 resolution with X11 as my display manager.
Im using the AppImage from the latest release as of date(1.1-dev). as previously @felipemanga states:

> This issue should be fixed in the new 1.1-dev releases, which enables GPU rendering and has faster software rendering as well. Please check if the situation has improved on your PCs.

I ran the 1.1dev AppImage with GPU Acceleration in the options on (300% screen scaling, and 100% UI elements scaling)
the entire canvas is laggy when using the mouse in full screen, this issue is partially fixed when I resize the window to a very tiny (likely 400x1000 resolution screen) then the FPS will suddenly get better.

I also ran `nvtop` to check if my intergrated intel GPU is doing anything, and LibreSprite does not seem to be within there.

The issue does not happen when mouse is on top of other parts of GUI(aka not on canvas)
