### ISSUE TITLE
INSTALL.md is missing informations about how to build for android

### ISSUE THREAD

**Issue by RebornOfc** [LibreSprite/LibreSprite#432]
Would appreciate if INSTALL.md is updated to give any information about how to compile libresprite for android.

**Comment by felipemanga** [comment]
It hasn't been documented there because it hasn't been set in stone yet. 
Basically, for MacOS/Linux:
- clone LibreSprite with submodules
- Install native dependencies: I know it needs at least libtinyxml2, not sure about the rest
- Build dependencies: `cd LibreSprite && mkdir build && cd build && cmake -G Ninja -DGEN_ONLY=ON .. && ninja && cd ..`
- Get Android dependencies: `git clone https://github.com/LibreSprite/ls-android-deps android`
- `cd android && sh ./gradlew build`

As for Windows... good luck!

**Comment by RebornOfc** [comment]
Thanks!
