### ISSUE TITLE
Not showing at start menu in windows.

### ISSUE THREAD

**Issue by yuyutsupoudel** [LibreSprite/LibreSprite#71]
App installs fine and is also working from "C:\Program Files (x86)\librespritestuff". It also shows at "Control Panel\Programs\Programs and Features" but application icon is not showing in start menu.

**Comment by maujin111** [comment]
I don't use windows but you could try this: 
1. press "windows key + R" 
2. write " %AppData%\Microsoft\Windows\Start Menu\Programs" then press enter, a window should pop up, let that window open. 
3. open a new window and go to"C:\Program Files (x86)\librespritestuff" 
4. copy libresprite.exe and paste it as shortcut on" %AppData%\Microsoft\Windows\Start Menu\Programs". 
5. restart your pc to apply changes.

**Comment by yuyutsupoudel** [comment]
ya thanks for suggestions. i did that but i think it should work automatically like every other window application.

**Comment by Ev1lbl0w** [comment]
I don't have much Windows experience either, but I suppose this should be done by the installer..?

**Comment by yuyutsupoudel** [comment]
I also don't have much experience with windows. Application is installed but does not appear in all apps menu. I can search it or uninstall it and i can use it from installation path but app does not appear at all app menu until i manually add.

**Comment by tom-corwin** [comment]
The shortcut is being created by the installer (as it should be), it is just being created in the same folder as the application (i.e. `C:\Program Files (x86)\librespritestuff\libresprite.exe - Shortcut`).

 It also will not work anyways because rather than pointing to the application `C:\Program Files (x86)\librespritestuff\libresprite.exe`, it points to `C:\Users\mints\LibreSprite\build\bin\libresprite.exe`.

**Comment by tom-corwin** [comment]
The issue lies here:
https://github.com/LibreSprite/LibreSprite/blob/73f138ff13acdd85017e1f6d2ed44d4b9ff6dca3/installer/installer.iss#L44-L46

I believe, based on [this part](https://jrsoftware.org/ishelp/index.php?topic=iconssection) of Inno Setup's documentation, you are missing `WorkingDir` parameters on both lines. I *think* a possible solution would be to replace those lines with:

```iss
 [Icons] 
 Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir : "{app}"
 Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir : "{app}"; Tasks: desktopicon 
```

**Comment by Shoozza** [comment]
Note the installer which proposes installation into the folder librespritestuff is not the innosetup installer but a proprietary installer (afaik) the innotsetup installer is currently not included in any downloads (not sure why)

**Comment by Zughy** [comment]
Fixed by ^
