### ISSUE TITLE
Did commit 7750982 introduce GPL incompatibilities?

### ISSUE THREAD

**Issue by jgyllinsky** [LibreSprite/LibreSprite#9]
I'm not sure that this fork isn't too new. Commit 7750982af6159d0bcb01336da915d93c88318886 appears to be the start of the change in the original Aseprite's direction. Shouldn't this repo be rolled back to that point before continuing? I'm not positive that the following commit d7d57667fc78849aa2a662742e23c06c3292570d doesn't introduce potential GPL incompatibilities.

**Comment by akien-mga** [comment]
I don't see any issue with commit 7750982. The added EULA in d7d5766 changed nothing for the license of the GPLv2 source code, which is the only thing we forked. We do not provide the "official binaries" of the original upstream, and therefore don't have to abide by the EULA.

**Comment by jgyllinsky** [comment]
I'm not a professional and cannot give any advice, but using d7d57667fc78849aa2a662742e23c06c3292570d makes me nervous as to me it seems like it straddles saying everything is GPL but also not at the same time. 

> "I don't see any issue with commit 7750982af6159d0bcb01336da915d93c88318886." - @akien-mga 

It isn't the that commit that is the issue so much as the following one, d7d57667fc78849aa2a662742e23c06c3292570d. In d7d57667fc78849aa2a662742e23c06c3292570d (02/16/16) the license changes to questionably-GPL-incompatible, I think. I am looking at the commits from "Commits on Feb 16, 2016" which at this moment can be found at https://github.com/aseprite-gpl/aseprite/commits/master?page=15 , although new commits added to project may change this page.


At commit 7750982af6159d0bcb01336da915d93c88318886 the project is only GPL. The project isn't just code, it is documentation and the like. I worry that the issue causing this fork may appear again at a later point if Aseprite/AsepriteTeam/David doesn't explicitly endorse forking at d7d57667fc78849aa2a662742e23c06c3292570d and releasing everything completely as standard GPL version 2.0. If we add or change the project significantly and then have to deal with this at a much later point, this issue, imo, could deadlock the project completely.

Furthermore, needing to have a Aseprite-GPL/AllegSprite/OpenSprite/fork-name indubitably will lead to non-Aseprite packagers being needed (to package Aseprite-GPL for Linux, Mac, Win, etc), which if I understood the license change notes correctly, played a role in the Aseprite Team's choice. I think it best to preventively avoid this.

**Comment by akien-mga** [comment]
I am not a lawyer, but I really don't think there is any issue with d7d5766. The licensing situation before this commit was:

- "This program is GPLv2". Whatever "program" means in the context of a full repository, and whether it applies to documentation files and things like that is beyond my knowledge and probably a legal grey area when there is no explicit mention of the license for all single files. All source files (C++ files) headers had the GPLv2 short text, which confirms their licensing. In my experience, it is generally assumed that such a broad license claim in the README applies to *everything* unless specified otherwise for individual files/folders.

The situation after the commit became:

1. The *source code* is GPLv2. Whether "source code" encompasses the same things as the previous "This program" claim, I can't tell, but I'm pretty sure that the common understanding would be "the contents of this source code repository, unless specified otherwise".
2. The *official releases* are under a proprietary EULA. "Official releases" mean pre-compiled binaries for the supported platforms that you can buy and download from the project's official website, i.e. that attached the project main developer and copyright holder. Those are derived *from* the source code, but do not taint it. If you make proprietary binaries from MIT code, the code stays MIT. Same with the GPLv2.
3. The *Steam releases* are distributed under a Steam EULA. Again, those are about pre-compiled binaries distributed via the Steam platform, and do not have anything to do with nor taint this repository.

The points 2. and 3. are in my opinion exceptions to the point 1., so it's relatively clear to me that the scope of point 1. is the same as the scope that the statement had before the commit d7d5766, i.e.: all the files in this repo which are not from third party projects and not with another explicit license are licensed under the GPLv2.

Maybe @dacap could confirm. I'm pretty sure this is a non-issue and there's nothing to be concerned about.

**Comment by dacap** [comment]
Hi there, the fork was done in the right place. The source code was still released under GPL terms + other licenses. So from d7d57667fc78849aa2a662742e23c06c3292570d I started sublicensing the code to create non-distributable binaries (EULA), and with the Steam license. But the code was licensed under GPL too. This is was only possible because we were not using third party GPL libraries as the note of the end said.

**Comment by akien-mga** [comment]
Forgot to close this issue back then, but since we have confirmation from the Aseprite author that the fork was done correctly, this issue is resolved.
